README.md, eks_rolling_update.py, lib/aws.py
_**Disclaimer**_: 
This PR might sound (too) opiniated.  However, this did solve a real problem we had. Hope you can benefit from it ;)
**Context**:
The current scaledown method leaves no control over which nodes are to be terminated.  The control is delegated over to the ASG, where good and bad can (and DO happen).  For instance, we were left with zero node for a minute when the ASG "choose" (for lack of better explaination) to terminate all the remaining nodes right after the scaledown/resume operations.  There is a better way IMHO.
**Proposition**:
As we already know which node just got terminated (`outdated['InstanceId']`), we can detach it from the ASG right after, and scaledown the desired value by 1 automatically through the api (`ShouldDecrementDesiredCapacity=True`).  No …
=> Replace scaledown by detaching EC2 from ASG

.gitignore, eks_rolling_update.py, lib/aws.py, requirements-tests.txt, requirements.txt, tests/fixtures/aws_response_launchtemplate.json, tests/fixtures/aws_response_launchtemplate_default.json, tests/fixtures/aws_response_launchtemplate_latest.json, tests/fixtures/get_launch_template.json, tests/test_aws.py, tests/test_aws_launchtemplate.py, tests/test_k8s.py
This adds support for Launch Templates with and without a Mixed Instances Policy.
Confirmed working with one of my `MixedInstancesPolicy` clusters. I still need to write tests, but I thought I'd create the PR early for feedback.
Fixes #10
=> Support for launch template

README.md, config.py, eks_rolling_update.py, lib/aws.py
- MacOS
- virtualenv with python 3.7.4
- wanted to use `eks-rolling-update` project against an EKS cluster just for testing the rolling out of new nodes
- `cluster-autoscaler` was not deployed
- got errors when the updater tried to operate on `cluster-autoscaler`
- no way to disable it because of the way environment variables were handled
```
#
#
$ export K8S_AUTOSCALER_ENABLED=false
$ python
Python 3.7.4 (default, Oct 12 2019, 18:55:28)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> v = os.getenv('K8S_AUTOSCALER_ENABLED', True)
>>> v
'false'
>>> v is True
False
>>> v is False
False
```
- k8s autoscaler operations are disabled by default
- added defaults for CA namespace and deployment name
- comply …
=> enable/disable CA and some environment vars handling fixes

README.md, config.py, lib/k8s.py
**Motivation**
There are a number of additional arguments to `drain` that would be useful to be able to control, in particular `--force=true` (to get rid of pesky standalone `Pod`s which currently break the tool, or `--grace-period` overrides etc).
Rather than add env configuration for each arg individually, it seems sensible to me to allow people to add on the to basic args already supplied that support automation.
This PR also fixes the boolean parsing within `config.py` which was incorrectly treating `export DRY_RUN=false` as Python `True` due to the way `bool(str)` works. Using `strtobool` gives [truthy style parsing](https://docs.python.org/3/distutils/apiref.html#module-distutils.util).
=> Add ability to add additional arguments to the kubectl drain function

README.md, config.py, eks_rolling_update.py, lib/aws.py
Fixes #22 by providing ability to disable waiting for detachment via `ASG_WAIT_FOR_DETACHMENT=false`. Default is true, same as previous behaviour.
Also made some minor code tidies to remove unnecessary casts; and add a shebang to allow the script to be run per the examples.
=> Make waiting for detachment of instances optional

README.md, config.py, eks_rolling_update.py, lib/aws.py
This PR adds support for using AutoScalingGroups termination policy (see [this](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-termination.html#default-termination-policy))
Reasons:
- have the option to leverage ASG termination policy to destroy older instances on scale down instead of overriding the ASG behaviour (currently, the script simulates the ASG behaviour by actually calling terminate/detach instance)
- faster upgrades -> no more time spent in terminating/detaching instances from ASG -> handled by ASG automatically (some sort of `fire-and-forget` approach)
- suitable for the majority of EKS + standard ASGs use cases where ASGs have a `Default` termination policy
Default value: `False` (disabled)
lib/aws.py changes:
- `count_all_cluster_instances` needed an …
=> Add support for using ASG termination policy

eksrollup/cli.py
Address the specific failure case outlined in #29 by setting the desired instances ASG tag appropriately just before node termination.
=> Handle draining failures better. Closes #29.

Dockerfile
The image used to have `bash`. I believe the use of multi-stage build in #36 made `bash` go away, which is a breaking change.
```sh
$ docker build --build-arg VERSION=1.0 -t rolling-update:master .
[...]
Successfully tagged rolling-update:master
$ docker run -it --entrypoint=/bin/sh rolling-update:master
/app # bash
/bin/sh: bash: not found
/app # which bash
/app # /bin/bash
/bin/sh: /bin/bash: not found
```
=> Add bash back to the image

eksrollup/lib/k8s.py
There is a use case in which this component should run inside Kubernetes. For that reason, we could leverage the in cluster configuration instead of the file. This PR adds this functionality.
=> Check for incluster configuration and then use kubeconfig

Dockerfile, README.md, eksrollup/cli.py, eksrollup/config.py, eksrollup/lib/aws.py
@crhuber This is a continuation of splitting #35 into multiple PRs.
This PR adds a mode 4 to the script which aims to roll nodes based on each ec2 instance's age (i.e. roll nodes older than x days). A new variable is added `MAX_ALLOWABLE_NODE_AGE` which defaults to 6 days as part of this new mode. The new mode checks for each instance launch date and replaces nodes older than `MAX_ALLOWABLE_NODE_AGE`. The purpose behind this is to ensure nodes running in a cluster are consistently refreshed regardless of configuration changes. 
Mode 4 follows the same pattern as mode 1 in order of execution: scale up and cordon the outdated nodes of each ASG one-by-one, before each is drained.
=> Adding Mode 4  (rolling nodes based on age)

README.md, eksrollup/config.py, eksrollup/lib/k8s.py
We have nodes in our cluster which do not belong to any autoscaling group, and need to be excluded from the node count when checking if the cluster is still healthy. Therefore, we need the EXCLUDE_NODE_LABEL_KEY configuration to be configurable when we execute the script.
=> Allow user to configure EXCLUDE_NODE_LABEL_KEYS

Dockerfile
Currently `make docker-dist version=1.0.DEV` fails with the following error due to missing `gcc` in the alpine image.
This PR adds `gcc` to fix the build.
```
Building wheel for multidict (PEP 517): started
Building wheel for multidict (PEP 517): finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpg_01hlzx
cwd: /tmp/pip-install-041nro4c/multidict
Complete output (43 lines):
**********************
* Accellerated build *
**********************
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/multidict
copying multidict/_multidict_py.py -> …
```
=> Fix broken build in Dockerfile

README.md, eksrollup/config.py, eksrollup/lib/aws.py, tests/fixtures/aws_response_shutting_down.json, tests/test_aws.py
Hi 👋 
Firstly, this is a great tool! Virtual 🍻  from me!
This PR adds the ability to override the default behaviour when checking that an instance is terminated.
It adds the env variable: `INSTANCE_WAIT_FOR_STOPPING` which will also check for "stopping" states (`shutting-down`, `stopping`) which will speed up a run considerably in the trust that AWS really will terminate the instance eventually.
Any feedback or improvements would be appreciated :) 
Thanks!
=> feat: allow user to override termination check

README.md, eksrollup/cli.py, eksrollup/config.py
Batching is disabled by default, however, if the BATCH_SIZE environment variable is specified, then eksrollup will scale the ASG up BATCH_SIZE nodes at a time.
=> Add simple batching

README.md, eksrollup/config.py, eksrollup/lib/aws.py
We have a usecase where we want to apply rolling update to only some of the ASGs that run critical applications, and the remaining ones could be updated separately in a different time window.
Currently there is no option to specify this from the tool. I have added the functionality in this PR in which there is environment variable "ASG_NAMES" which can be given list of space-delimited ASG names. Only these provided ASGs will be processed for rolling update out of the ASGs attached to the cluster (i.e. those having the tag kubernetes.io/cluster/<cluster_tag> = owned). If "ASG_NAMES" is left empty, all cluster ASGs will be processed.
Please review this PR, and thanks for tool this works pretty well.
=> Feature to specify selective AutoScaling Groups for rolling update

eksrollup/cli.py, eksrollup/lib/k8s.py, requirements-tests.txt, tests/fixtures/example-kube-config.yaml, tests/test_k8s.py
This PR makes two changes related to the way the Kubernetes python client is configured:
1. Fixes behaviour with Kubernetes python client v12 (fixes #72)
2. Adds support for use behind TLS passthrough forward proxies via standard OS env vars, similar to `kubectl` (fixes #64)
The Kubernetes python client v12 seems to have somehow changed the way the default configuration works; such that if you create a `Configuration()` object you don't get the default configuration by default.
See https://github.com/kubernetes-client/python/issues/1284 and https://github.com/kubernetes-client/python/commit/b4d11b02a3479e63957a729614a616002f13e9c4#diff-59aff6ce4d28aa662f8b411b9d0dfe4f3e949c32a5edaf8e08905b58e7a41ee3L69-R71
Since we don't actually try to customise the `ApiClient` or the `Configuration` at …
=> Ensure k8s config compatibility with kubernetes==12 python client + support proxies

README.md, eksrollup/config.py, eksrollup/lib/k8s.py
when running the script in a cluster containing misconfigured podDisruptionBudgets (e.g. minAvailable: 1 and only one replica running) or just containers which aren't running, the script fails while draining nodes. we were facing this behaviour in development and testing environments.
to be able to complete a rolling update in such clusters we've added an optional enforced_draining which retries draining a node after failing while evicting pods.
example execution output is attached:
[eks-rolling-update_enforced-draining.txt](https://github.com/hellofresh/eks-rolling-update/files/5634734/eks-rolling-update_enforced-draining.txt)
=> feature to enforce draining of nodes when pods cannot be evicted

README.md, eksrollup/lib/k8s.py, requirements.txt, tests/test_k8s.py
This PR improves the proxy support in #73 to give some flexibility in when the proxy is used. In our case we have the following requirements:
1. Calls to AWS APIs must use `HTTP_PROXY` since we have no direct internet access in our VPCs 
2. Calls to k8s cluster must not go via `HTTP_PROXY`. 
In this case we must have `HTTP_PROXY` set but this causes the rolling update code to try and also go via `HTTP_PROXY`. `NO_PROXY` is configured to include the k8s cluster endpoint but isn't adhered to here. 
I wanted to adhere to `NO_PROXY` originally but I couldn't see a good way get `servers` value from kubernetes python client once it loaded config, to see if it matched something in `NO_PROXT`. I also didn't think it would be a good idea read kube config independently. 
For the above reasons I …
=> disable proxy for k8s only when configured.

eksrollup/cli.py
I've removed this if statement which I'm pretty sure is an error but it would be useful if you could review @caphrim007.
It prevented the script working on one of my clusters where the desired (doubled) capacity of my first ASG was 8 and the total number of nodes in the cluster was also 8. This is with batch_size not set.
Adding an extra
```
else:
current_capacity = desired_capacity
```
To the end of `if asg_instance_count != desired_capacity:` would also work but I can't see any case in which this case is useful. The logic inside `if batch_size` seems to take care of every case anyway from what I can tell.
Here are the logs:
```
2020-10-16 13:35:52,307 INFO     Instance id i-08dd62642ff5520a6 launch template version of '17' does not match asg launch template version of '18'
2020-10-16 …
```
=> Fix bug with ASG scale up logic

eksrollup/cli.py
When using DRY_RUN environment variable instead of the -p flag ASG modification and tag modification is skipped but it goes into a loop of waiting for the ASG to scale and checking cluster health which eventually fails.  This change makes DRY_RUN function the same as the -p flag.
To reproduce run `DRY_RUN=true eks_rolling_update.py --cluster_name CLUSTER_NAME`
```
2021-02-04 09:25:58,123 INFO     Describing autoscaling groups...
2021-02-04 09:25:58,753 INFO     Pausing k8s autoscaler...
2021-02-04 09:25:58,987 INFO     K8s autoscaler modified to replicas: 0
2021-02-04 09:25:59,332 INFO     *** Checking autoscaling group test-all-pods2021011314330308490000001c ***
2021-02-04 09:25:59,332 INFO     Describing launch template for test-all-pods20210113143259732300000019...
2021-02-04 …
```
=> Fix DRY_RUN behavior

README.md, eksrollup/config.py, eksrollup/lib/k8s.py, tests/test_k8s.py
The # of env vars & complexity of configuration has grown quite a lot. Without consistent semantic prefixing of the env vars, or a structured config approach it's getting a bit difficult to understand the options we have when configuring the tool.
To try and improve this, this PR
- removes an unused config option
- ensures all custom tool env vars are defined within `config.py` and parsed off the env consistently (principle of least-surprise)
- adds the missing documentation for `TAINT_NODES=true`
- tweaks some of the wording for conciseness
- restructures the env vars to make them easier to understand and work with
Possibly easiest to review with the "rich diff" of the markdown.
=> Tidy configuration & improve readme readability

.github/workflows/deploy.yaml
Fixes gh actions error
>The workflow is not valid. .github/workflows/deploy.yaml (Line: 31, Col: 12): Unrecognized named-value: 'VERSION'. Located at position 1 within expression: VERSION
=> GH Fix Version Variable

eksrollup/cli.py, eksrollup/lib/aws.py, tests/test_aws_launchtemplate.py
We recently moved from Launch Configurations to Launch Templates and had instances without LaunchTemplate configuration in an ASG that used LaunchTemplates. This resulted in an error when trying to compare launch template versions on those instances.
This PR fixes that and also fixes up a small bug in plan output.
=> fix: handle missing launch templates

eksrollup/lib/aws.py
Uses existing code to check if the node should be excluded during the desired node count calculation
=> Fix bug during cluster health check
